### ISSUE TITLE
According to the code of the example and tried it, the following error will be reported

### ISSUE THREAD

**Issue by wulaizi** [Type-Any/react-native-clear-cache#8]
ClearCache.getAppCacheSize was called with 1 arguments but expects 0 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

**Comment by shhong7757** [comment]
Sorry to have left the repo unattended for a long time.

Overall, the code has been modified.

The problem you mentioned has been resolved.

Thank you.

We will close the issue.
